### ISSUE TITLE
compilation on ubuntu 16.04 fails

### ISSUE THREAD

**Issue by nightrid3r** [lemoncoin-project/lemoncoin#5]

**Comment by nightrid3r** [comment]
Making all in src
make[1]: Map '/home/michel/lemoncoin-1.0.0/src' wordt binnengegaan
make[2]: Map '/home/michel/lemoncoin-1.0.0/src' wordt binnengegaan
  CXX      primitives/libbitcoinconsensus_la-transaction.lo
  CXX      libbitcoinconsensus_la-pubkey.lo
  CXX      script/libbitcoinconsensus_la-bitcoinconsensus.lo
  CXX      script/libbitcoinconsensus_la-interpreter.lo
  CXX      script/libbitcoinconsensus_la-script.lo
  CXX      libbitcoinconsensus_la-uint256.lo
  CXX      libbitcoinconsensus_la-utilstrencodings.lo
  CXXLD    libbitcoinconsensus.la
/usr/bin/ar: `u' modifier ignored since`D' is the default (see `U')
  CXX      lemoncoind-bitcoind.o
  CXX      libbitcoin_server_a-addrman.o
  CXX      libbitcoin_server_a-alert.o
/tmp/ccWvddj5.s: Assembler messages:
/tmp/ccWvddj5.s:273489: Error: unknown pseudo-op:`.mong'
Makefile:3889: recept voor doel 'libbitcoin_server_a-alert.o' is mislukt
make[2]: **\* [libbitcoin_server_a-alert.o] Fout 1
make[2]: Map '/home/michel/lemoncoin-1.0.0/src' wordt verlaten
Makefile:6944: recept voor doel 'all-recursive' is mislukt
make[1]: **\* [all-recursive] Fout 1
make[1]: Map '/home/michel/lemoncoin-1.0.0/src' wordt verlaten
Makefile:630: recept voor doel 'all-recursive' is mislukt
make: **\* [all-recursive] Fout 1

**Comment by withthelemons** [comment]
What version of GCC you have?

**Comment by nightrid3r** [comment]
gcc 5.4.0 ubuntu 16.04

**Comment by withthelemons** [comment]
Just tested on fresh Ubuntu 16.04 and there were no problems, closing.
